### PR TITLE
Wip nzmap

### PR DESCRIPTION
**Pull request by gclitheroe**
Hi Howard,

please could you have a look at this?  Especially `nzmap/nzmap.go`.  Do you think we can replace `geonet-web/nzmap` with this?  It would mean moving the quake and impact functions in `geonet-web/nzmap/nzmap` into something like `geonet-web/origin/quake.go` and just using `map180/nzmap` for getting the base maps.

Thanks,
Geoff

### CODE REVIEW

**Comment by junghao** [comment]
The nzicon.go's viewBox should be "0 0 100 125".
However, setting viewBox to 100x125 causes the svg trying to fill the column. See image below:

screen shot 2016-02-17 at 2 22 20 pm

As you can see the left window is the existing icon with width="100" height="125" attribute. And the right window is the icon with only viewBox="0 0 100 125" attribute (without width/height attribute). 

So I prefer change the nzicon svg to has width/height attribute.

**Comment by gclitheroe** [comment]
I think I've understood what you mean.  The viewbox is the current best way to make SVG images resize responsively.  Done this way it inherits is size from the parent.  Is there anything that can be done with the columns for size?

For something like an icon map though I can see the argument for setting width and height so don't spend to long on it.

**Comment by junghao** [comment]
OK if you think it'll be better we make a "responsive icon" so we can keep using it in the future, then I'll try  setting its size from the html which embeds this svg.

**Comment by gclitheroe** [comment]
ok.  But don't try to hard!  I think the icon is so small making it responsive may not be worth it.

THe medium map it is worth it (and it's what I did).

Shall I just put the width and height back on the icons, instead of the view box?

**Comment by junghao** [comment]
I think it's ok without width and height. Just change viewBox="0 0 100 125" and everything works good for me.

https://github.com/GeoNet/geonet-web/pull/116

**Comment by gclitheroe** [comment]
Sorry - I'm a bit lost.  Do I need to make any changes in this PR or can it be merged? @junghao

**Comment by junghao** [comment]
Simply change nzicon's viewBox to "0 0 100 125".

**Pull request merged**
